/* Generates server/src/context.js — the trip knowledge the chat assistant
   answers from — straight out of the app's own data files, so the
   assistant can never drift from the published itinerary.

   Run after editing js/data/trip.js:
     node tools/gen-context.mjs
*/
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const { TRIP, ESSENTIALS, TRIP_STATS } = await import(join(here, '../js/data/trip.js'));
const { COUNTRY_NUMBERS, RENTAL, REQUIRED_DOCS } = await import(join(here, '../js/data/emergency.js'));

const en = x => (x == null ? '' : (typeof x === 'string' ? x : x.en));

const lines = [];
lines.push('EURORIDE 2026 — TRIP FACTS');
lines.push('11-day Harley-Davidson group ride (about 18 riders, the "Muñecos" crew), Aug 20-30 2026.');
lines.push('Bikes are rented from EagleRider Milan (pickup day 1, drop-off day 11, return with a full tank).');
lines.push('Route: Milan -> Splügen Pass -> Bormio -> Stelvio & Dolomites -> Munich -> Alsace -> Grimsel Pass -> Lake Como -> Milan.');
lines.push('Headline stats: ' + TRIP_STATS.map(s => `${s.value} ${en(s.label)}`).join(', ') + '.');
lines.push('');

for (const d of TRIP) {
  lines.push(`DAY ${d.n} — ${d.iso} (${en(d.date)}): ${en(d.title)}`);
  lines.push(`  Route: ${en(d.route)}`);
  const bits = [];
  if (d.km) bits.push(`distance ${en(d.km)}`);
  if (d.time) bits.push(`ride time ${en(d.time)}`);
  if (d.high) bits.push(`high point ${d.high.m} (${en(d.high.name)})`);
  if (bits.length) lines.push('  ' + bits.join(' · '));
  lines.push(`  ${en(d.desc)}`);
  if (d.lodging && d.lodging.name) {
    let lodging = `  Lodging: ${en(d.lodging.name)} (suggestion, not booked)`;
    if (d.lodging.url) lodging += ` — booking link: ${d.lodging.url}`;
    lines.push(lodging);
  }
  if (d.mapUrl) lines.push(`  Route map: ${d.mapUrl}`);
  if (d.options) {
    for (const o of d.options) {
      lines.push(`  Option: ${en(o.name)}${o.km ? ` (${o.km})` : ''} — ${en(o.blurb)}`);
    }
  }
  if (d.notes) {
    lines.push(`  Fuel: ${en(d.notes.fuel)}`);
    lines.push(`  Tolls: ${en(d.notes.tolls)}`);
    lines.push(`  Road/weather: ${en(d.notes.road)}`);
    lines.push(`  Food: ${en(d.notes.food)}`);
  }
  lines.push('');
}

lines.push('BEFORE YOU ROLL (tolls, vignettes, weather, lodging philosophy):');
for (const e of ESSENTIALS) {
  lines.push(`- ${en(e.title)}: ${en(e.body).replace(/<[^>]+>/g, '')}`);
}
lines.push('');

lines.push('EMERGENCY NUMBERS (112 works in all five countries):');
for (const c of COUNTRY_NUMBERS) {
  lines.push(`- ${en(c.name)}: ` + c.numbers.map(n => `${en(n.label)} ${n.tel}`).join(', '));
}
lines.push(`- Bike rental: ${RENTAL.name}. ${en(RENTAL.note)}`);
lines.push('Documents to carry on the bike: ' + REQUIRED_DOCS.map(en).join('; ') + '.');

const context = lines.join('\n');

const out = `/* AUTO-GENERATED by tools/gen-context.mjs — do not edit by hand.
   Regenerate after changing js/data/trip.js:  node tools/gen-context.mjs */
export const TRIP_CONTEXT = ${JSON.stringify(context)};
`;

writeFileSync(join(here, '../server/src/context.js'), out);
console.log(`server/src/context.js written (${context.length} chars)`);
